# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-alpine

WORKDIR /app

# Copy source code
COPY . /app

# Install dependencies explicitly from pyproject.toml
RUN pip install --no-cache-dir httpx "mcp[cli]>=1.4.1" requests

# Expose port if needed (not needed for stdio transport)

# Default command: run bot.py with a placeholder webhook; overridden by Smithery startCommand
CMD ["python", "bot.py", "--webhook", "http://example.com/webhook#mysecret"]
